### ISSUE TITLE
Handle merge conflict with identical roots

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/node-playground#21]
When two roots are received from the same user pointing to the same ethereum block in the `rootBlock` value, the [design doc](https://farcasterxyz.notion.site/Spec-Farcaster-Message-c71fa4c4334542e9a3dc678be4df6fe2) says that we should keep the roots with the lowest lexicographical order. This method was chosen because it allows a deterministic way to resolve conflicts that can be performed independently by each node. 

A good solution would: 

1. Choose an algorithm for [lexicographical ordering](https://en.wikipedia.org/wiki/Lexicographic_order) of hash values
2. Implement the logic to order it in [the addRoot function of the engine](https://github.com/farcasterxyz/node-playground/blob/main/src/engine/index.ts#L47)
3. Write [tests](https://github.com/farcasterxyz/node-playground/blob/main/src/engine/engine.root.test.ts#L200) to validate the behavior. 

The important part here is that we have defined lexicographical in a formal way such that anyone implementing this in another language knows exactly how the comparison function should work, and even knows what tests to run against such an algorithm to ensure that it is working correctly.

**Comment by koloz193** [comment]
currently working through this. first attempt will be to model after C's `strcmp` which compares strings based on the ascii values of the char at each index.

**Comment by varunsrin** [comment]
ascii value comparison seems like the right approach. if javascript's native comparison does the same thing, maybe we're all set and just need to write tests to make the behavior clear.

**Comment by koloz193** [comment]
as stated here https://stackoverflow.com/questions/56094122/compare-two-strings-with-and-operators-in-javascript it says the standard splits it into 16 bit values where as ascii uses 7. prob worth explicitly using ascii IMO
